### ISSUE TITLE
Update docs.platforme.com

### ISSUE THREAD

**Issue by msp-platforme** [ripe-tech/ripe-api#28]
## Rationale

RIPE API hasn't been updated as much as RIPE SDK, so we must catch up on that debt.

## Description

- Find out what documentation is missing - docs.platforme.com
- Review the existent documentation
- Update the documentation

## Estimation

| Discipline | Estimation |
| --- | --- |
| **Software Development + QA** | 5 days |

**Comment by BeeMargarida** [comment]
Due diligence finds:

# Incomplete/wrong docs

* Render Endpoints
    * Mask
        * `model` is not mandatory (it should be)
        * Default `size` is not correct (depends on the build)
    * Swatch
        * Missing `variant` parameter

* Config Endpoints
    * Info
        * missing `version`, `initials`, `engraving`, `initials_extra`, `size`, `gender`, `meta`, `params`, `guess`
    * Price
        * missing `version`
    * Availability
        * missing `version`
    * SKU
        * `initials_extra` with the wrong description, missing `size`, `gender`
    * Check what the resources contain

* SKU Endpoints
    * Create
        * Point to a table containing the contents of a spec in the resources

* Brand Enpoints
  * Mesh
    * Find a better way to return the mesh file
  * Config & Spec
    * missing `safe`, `logic`
  * Logic
    * change `method_name` to `method`
  * Logic method
    * remove `groups` word

* Order Enpoints
    * Import
      * Mauro's PR - https://github.com/ripe-tech/ripe-api-docs/pull/39
      * Added missing parameters



# Missing Docs
* Account
* Authentication
  * Daniel's PR - https://github.com/ripe-tech/ripe-api-docs/pull/45
* Build
  * The install/uninstall/switch won't enter the documentation, since they are too "techy"
  * /builds/<str:name>/fonts
  * /builds/<str:name>/fonts/<regex('[a-zA-Z0-9]+'):font>.<str:format>
  * /builds/<str:name>/fonts/<regex('[a-zA-Z0-9]+'):font>
  * /builds/<str:name>/locale.csv
  * /builds/<str:name>/locale/keys
  * /builds/<str:name>/locale/template
  * /builds/<str:name>/locale/<str:locale>
  * /builds/<str:name>/locale/<str:locale>/values
* Render
  * Most swatch endpoints
  * /compose/clear
* Translate
  * /translate
* Config
  * /config
  * /config/prices
  * /config/defaults/<str:model>
* Country Group
* Design
* Email?
* History
* Justification
* Locale
  * POST /locale
* Model
* Notify Info?
* Order
  * /orders (List)
  * /order (Create)
  * /orders/search
  * /orders/<number> (Delete)
  * /orders/<int:number>/attachments
  * /orders/<int:number>/attachments/<int:attachment_id>
  * /orders/<int:number>/attachments/count
  * /orders/<int:number>/attachments (POST)
  * /orders/<int:number>/notes
  * /orders/<int:number>/waybill
  * /orders/<int:number>/return_waybill
  * /orders/<int:number>/log
  * /orders/<int:number>/states
  * (all chat and attachments endpoints)
  * /orders/<int:number>/price
  * /orders/<int:number>/transport
  * (all state changes endpoints)
  * (all set enpoints)
  * …
* Plugin
* Profile
* Sizes (some)
  * Nuno's PR (locales) - https://github.com/ripe-tech/ripe-api-docs/pull/50
* Factory Rules
  * Mauro's PR - https://github.com/ripe-tech/ripe-api-docs/pull/49
* Letter Rules
  * Mauro's PR - https://github.com/ripe-tech/ripe-api-docs/pull/49
* Price Rules
  * Mauro's PR - https://github.com/ripe-tech/ripe-api-docs/pull/49
* Transport Rules
  * Mauro's PR - https://github.com/ripe-tech/ripe-api-docs/pull/49

**Comment by joamag** [comment]
This is now considered done
